### ISSUE TITLE
Expvpn

### ISSUE THREAD

**Issue by coligall** [ag-pacier/ExpressVPN#1]

**Comment by ag-pacier** [comment]
My first issue, and it's blank! Not sure if that's a win or not.

This is a good reminder I need to update the ExpressVPN app on the container. I'll give you the weekend to let me know if you found an issue that I can address. If I don't hear by the time I check on Monday, I'll close the issue.

By all means, if you want to open a new issue, please do!

**Comment by ag-pacier** [comment]
Left it up for longer because I forgot about it and since no new comments... closed!
